USE DATABASE CONTROL_PLANE_DB;
USE SCHEMA CONTROL_PLANE_MONITORING;

CREATE OR REPLACE TABLE RUN_LOG (
    RUN_ID      STRING,
    WORKFLOW    STRING,
    STATUS      STRING,
    DETAILS     VARIANT,
    CREATED_AT  TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT  TIMESTAMP_NTZ
);
