USE DATABASE CONTROL_PLANE_DB;
USE SCHEMA CONTROL_PLANE_CONFIG;

CREATE OR REPLACE TABLE POLICIES (
    POLICY_NAME   STRING,
    DESCRIPTION   STRING,
    CONDITIONS    VARIANT,
    ACTIONS       ARRAY
);

INSERT INTO POLICIES (POLICY_NAME, DESCRIPTION, CONDITIONS, ACTIONS)
VALUES
(
  'DRIFT_POLICY_FRAUD_MODEL',
  'Trigger retraining when fraud model drift exceeds 0.15',
  OBJECT_CONSTRUCT('max_drift', 0.15),
  ARRAY_CONSTRUCT('trigger_retrain', 'notify_owner')
);
